### PR TITLE
stop-list for broken metrics

### PR DESCRIPTION
**Pull request by mheffner**
Rebased merge of: https://github.com/librato/statsd-librato-backend/pull/35

### CODE REVIEW

**Comment by mheffner** [comment]
@scalp42 Can you give this a try?

**Comment by obfuscurity** [comment]
Looks good to me. Would've been nice to add retry logic for that initial failure, but it's not a blocker. I :heart: that @overplumbum included a test, thanks so much.

**Comment by scalp42** [comment]
Any hints on how to test this? We're running into the issue right now, StatsD is reporting a negative `counter_rate` (the counter is `-1`) and Librato is dropping the payload.

Feels like a bug in StatsD or something because I have no clues how a counter_rate can be negative.

Any insight on how to test this PR lets say with StatsD cookbook from you guys? (I think we can only install straight from npm)

**Comment by mheffner** [comment]
@scalp42 I went ahead and merged this and cut a 0.1.7 release. Want to give that a shot?

(no idea on the counter_rate problem, is it possible a client is sending a bad rate value?)

**Comment by scalp42** [comment]
@mheffner I'm running the latest version (`statsd-librato-backend@0.1.7`) and I'm still seeing the issue unfortunately, if you have any idea:

```
20 Aug 18:13:13 - LOG_ERR: Failed to post to Librato: HTTP 400: {"errors":{"params":{"value":["must be positive"],"name":["servers.jmxtrans.memorypool.metaspace.usage_max"]}},"request_time":1440094393}
```

**Comment by mheffner** [comment]
@scalp42 Oh, so it looks like this PR was targeted towards the scenario of sending a counter for a gauge metric and vice-versa. Are you using `countersAsGauges: false`? How many counter metrics do you have, could you possibly convert them to gauges?

**Comment by scalp42** [comment]
Oh I see, I thought it was for the whole payload in general. Indeed, I'm using `"countersAsGauges": false,`, I need to read up on what the change back to true would involve (I think deleting the old counter metrics to get the new type as gauge).

**Pull request merged**
