### PR TITLE
describe writeToLegacy option

### PR DESCRIPTION
**Pull request by niklibrato**

### CODE REVIEW

**Comment by stevenscg** [comment]
LGTM! I have a legacy account and spent a few days reverting back to the 0.1.x branch of this module on some recently provisioned machines that picked up the 2.x versions. I'll be trying out the writeToLegacy option with 2.x soon.

**Comment by niklibrato** [comment]
@bryanmikaelian going to revisit this to highlight that it is better to use 1.x if the account isn't on tags.

**Comment by gmckeever** [comment]
@niklibrato If `writeToLegacy` is flagged on does the user also have to include a configured source? The latest readme is lacking documentation on configuring the source so this may be helpful to include.

**Comment by niklibrato** [comment]
@bryanmikaelian good point elaborating a little more. 
@gmckeever not sure really.. also worth investigating..

**Comment by niklibrato** [comment]
Just realized that the options part is completely messed up. I'll fix it.

**Comment by niklibrato** [comment]
@bryanmikaelian @gmckeever can you please review?

**Comment by niklibrato** [comment]
@stevenscg if your Librato account doesn't support tags, we recommend you use the 1.x [branch](https://github.com/librato/statsd-librato-backend/tree/branch-0.1.x) rather than the writeToLegacy option.

**Comment by stevenscg** [comment]
@niklibrato Got it. Thanks.

**Pull request merged**
